# Vendored from https://gitlab.com/maximilianoPizarro/connectivity-link (developer-hub)
enabled: true
clusterDomain: ""
gitopsRevision: "main"
userCount: 200
litellmUrl: "http://openshift-mcp-server-litellm.openshift-lightspeed.svc:4000/v1"
litellmModel: "deepseek-r1-distill-qwen-14b"
litellmApiKey: "sk-openshift-mcp-1234"
