---
type: showroom

default_width: 30
persist_url_state: true

view_switcher:
  enabled: true
  default_mode: split

tabs:
  - name: Developer Hub
    url: 'https://backstage-developer-hub-developer-hub.{cluster_domain}'

  - name: Terminal
    url: '#terminal'
