{{- range (list "apicast-scenario-1" "apicast-scenario-2" "apicast-scenario-3" "apicast-scenario-4") }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ . }}
  labels:
    app.kubernetes.io/managed-by: gateforge
    gateforge.io/apicast-scenario: "true"
  annotations:
    argocd.argoproj.io/sync-wave: "0"
{{- end }}
