apiVersion: kuadrant.io/v1
kind: AuthPolicy
metadata:
  name: ${{values.name}}-auth
  namespace: ${{values.namespace}}
  labels:
    app.kubernetes.io/name: ${{values.name}}
    backstage.io/kubernetes-id: ${{values.name}}
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: ${{values.name}}-route
  rules:
    authentication:
      api-key-auth:
        apiKey:
          selector:
            matchLabels:
              app.kubernetes.io/name: ${{values.name}}
              kuadrant.io/apikeys-by: api-key
        credentials:
          authorizationHeader:
            prefix: "APIKEY"
