apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gitea-scc-anyuid
  annotations:
    argocd.argoproj.io/sync-wave: "1"
rules:
  - apiGroups: ["security.openshift.io"]
    resources: ["securitycontextconstraints"]
    resourceNames: ["anyuid"]
    verbs: ["use"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: gitea-scc-anyuid
  annotations:
    argocd.argoproj.io/sync-wave: "1"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: gitea-scc-anyuid
subjects:
  - kind: ServiceAccount
    name: gitea
    namespace: gitea
  - kind: ServiceAccount
    name: default
    namespace: gitea
