clusterDomain: "apps.cluster.example.com"

global:
  postgresql:
    auth:
      postgresPassword: "supersecretpassword"
      username: "neuralbank"
      password: "neuralbank123!"
      database: "neuralbank"

backend:
  image:
    repository: quay.io/maximilianopizarro/neuralbank-backend
    tag: "latest"
    pullPolicy: Always
  service:
    port: 8080
  replicaCount: 1

frontend:
  image:
    repository: quay.io/maximilianopizarro/neuralbank-front
    tag: "pkce"
    pullPolicy: Always
  service:
    port: 8080
  replicaCount: 1

threescale:
  adminPortalHost: "3scale-admin.3scale-system.svc.cluster.local"
  providerAccountRef: "threescale-provider-account"
