schemaVersion: 2.2.2
metadata:
  name: ${{values.name}}
  version: 1.0.0
  displayName: ${{values.name}}
  description: ${{values.description}}
  language: YAML
  projectType: Gateway
components:
  - name: tools
    container:
      image: registry.redhat.io/devspaces/udi-rhel8:3.18
      memoryLimit: 1Gi
      cpuLimit: "1"
      mountSources: true
commands:
  - id: apply
    exec:
      component: tools
      commandLine: oc apply -f manifests/ -n ${{values.namespace}}
      workingDir: ${PROJECT_SOURCE}
      group:
        kind: run
        isDefault: true
