apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: ${{values.name}}-external-route
  namespace: ${{values.namespace}}
  labels:
    app.kubernetes.io/name: ${{values.name}}
    backstage.io/kubernetes-id: ${{values.uniqueName}}
  annotations:
    haproxy.router.openshift.io/timeout: 300s
spec:
  host: ${{values.name}}.${{values.clusterDomain}}
  port:
    targetPort: http
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: ${{values.name}}-gateway-istio
    weight: 100
