apiVersion: v1
kind: Namespace
metadata:
  name: 3scale-system
  annotations:
    argocd.argoproj.io/sync-wave: "0"
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: 3scale-operator-group
  namespace: 3scale-system
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  targetNamespaces:
    - 3scale-system
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: 3scale-operator
  namespace: 3scale-system
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  channel: threescale-2.15
  installPlanApproval: Automatic
  name: 3scale-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: 3scale-argocd-role
  namespace: 3scale-system
  annotations:
    argocd.argoproj.io/sync-wave: "1"
rules:
  - apiGroups: [""]
    resources: ["*"]
    verbs: ["*"]
  - apiGroups: ["apps"]
    resources: ["*"]
    verbs: ["*"]
  - apiGroups: ["apps.3scale.net"]
    resources: ["*"]
    verbs: ["*"]
  - apiGroups: ["capabilities.3scale.net"]
    resources: ["*"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: 3scale-argocd-binding
  namespace: 3scale-system
  annotations:
    argocd.argoproj.io/sync-wave: "1"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: 3scale-argocd-role
subjects:
  - kind: ServiceAccount
    name: openshift-gitops-argocd-application-controller
    namespace: openshift-gitops
---
apiVersion: apps.3scale.net/v1alpha1
kind: APIManager
metadata:
  name: 3scale
  namespace: 3scale-system
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  wildcardDomain: {{ .Values.wildcardDomain }}
  resourceRequirementsEnabled: false
  system:
    fileStorage:
      persistentVolumeClaim:
        storageClassName: null
  zync:
    appSpec:
      replicas: 1
    queSpec:
      replicas: 1
  backend:
    listenerSpec:
      replicas: 1
    workerSpec:
      replicas: 1
    cronSpec:
      replicas: 1
  apicast:
    stagingSpec:
      replicas: 1
    productionSpec:
      replicas: 1
