apiVersion: extensions.kuadrant.io/v1alpha1
kind: OIDCPolicy
metadata:
  name: ${{values.name}}-oidc
  namespace: ${{values.namespace}}
  labels:
    app.kubernetes.io/name: ${{values.name}}
    backstage.io/kubernetes-id: ${{values.uniqueName}}
spec:
  auth:
    tokenSource:
      authorizationHeader:
        prefix: Bearer
  provider:
    clientID: neuralbank-frontend
    issuerURL: https://rhbk.${{values.clusterDomain}}/realms/neuralbank
  targetRef:
    group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: ${{values.name}}-route
